- name: configure dns
  hosts: localhost
  tags: dns
  roles:
    - dns

- name: perform core tasks
  hosts: localhost
  tags: core
  roles:
    - core

- name: install/configure tinyproxy
  hosts: localhost
  tags: tinyproxy
  roles:
    - tinyproxy

- name: install/configure yum-cron
  hosts: localhost
  tags: yum-cron
  roles:
    - yum-cron
