- name: install core packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - vim-enhanced
    - git
    - ansible
    - cronie
    - rsyslog

- name: start/enable crond
  service:
    name: crond
    state: started
    enabled: yes

- name: start/enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes
